version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/web/zip
    overwrite: yes

#permissions:
#  - object: /
#    owner: ubuntu
#    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60